name = "glassine"
compatibility_date = "2024-01-01"
pages_build_output_dir = "./dist"

# Assets configuration for wrangler versions upload
[assets]
directory = "./dist"

[env.production]
vars = { ENVIRONMENT = "production" }

[[d1_databases]]
binding = "DB"
database_name = "glassine-db"
database_id = "placeholder-create-with-wrangler-d1"

[[kv_namespaces]]
binding = "KV"
id = "placeholder-create-with-wrangler-kv"
